# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_requests', to='itis_manage.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='NGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('third_name', models.CharField(max_length=40)),
                ('birth_date', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('practice', models.IntegerField()),
                ('exam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_exam', models.CharField(choices=[('EX', 'Экзамен'), ('ND', 'Недифференцированный зачет'), ('DT', 'Дифференцированный зачет')], default='EX', max_length=2)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='itis_manage.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STUDYING', 'Учится'), ('ACADEMIC LEAVE', 'В академическом отпуске'), ('DEDUCTED', 'Отчислен'), ('EXPELLED', 'Отчислился')], default='STUDYING', max_length=14)),
                ('form_of_education', models.CharField(choices=[('BUDGET', 'Бюджет'), ('GRANT', 'Грант'), ('CONTRACT', 'Договор')], default='BUDGET', max_length=8, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='itis_manage.NGroup')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_student', to='itis_manage.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Практика'), ('L', 'Лекция')], default='L', max_length=1)),
                ('group', models.ManyToManyField(to='itis_manage.NGroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itis_manage.Person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itis_manage.Subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_semesters', to='itis_manage.Subject'),
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itis_manage.Student'),
        ),
        migrations.AddField(
            model_name='progress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itis_manage.Subject'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ManyToManyField(to='itis_manage.Status'),
        ),
        migrations.AddField(
            model_name='laboratoryrequests',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests_for_labs', to='itis_manage.Student'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_laboratories', to='itis_manage.Person'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itis_manage.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together=set([('semester', 'subject')]),
        ),
    ]
