# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itis_manage', '0002_auto_20170710_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='standing',
            field=models.CharField(choices=[('STUDYING', 'Учится'), ('ACADEMIC LEAVE', 'В академическом отпуске'), ('DEDUCTED', 'Отчислен'), ('EXPELLED', 'Отчислился')], default='STUDYING', max_length=14, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ManyToManyField(related_name='status_persons', to='itis_manage.Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_education',
            field=models.CharField(choices=[('BUDGET', 'Бюджет'), ('GRANT', 'Грант'), ('CONTRACT', 'Договор')], default='BUDGET', max_length=8, null=True, verbose_name='Форма обучения'),
        ),
    ]
