# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('itis_manage', '0003_auto_20170710_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Город')),
            ],
        ),
        # Try to insert this, if you are have existing students
        migrations.RunSQL("INSERT INTO itis_manage_city (name) VALUES ('Акташ');"),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_persons',
                                    to='itis_manage.City'),
            preserve_default=False,
        ),
    ]
