# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itis_manage', '0008_auto_20170711_2130'),
        ('itis_manage', '0004_auto_20170711_2334'),
    ]

    operations = [
    ]
