# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itis_manage', '0009_merge_20170712_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magistrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=60, verbose_name='Предыдущее место обучения')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magistr_student', to='itis_manage.Student')),
            ],
        ),
        migrations.AddField(
            model_name='ngroup',
            name='curator',
            field=models.ManyToManyField(related_name='curator_group', to='itis_manage.Person'),
        ),
        migrations.AddField(
            model_name='ngroup',
            name='year_of_foundation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ManyToManyField(to='itis_manage.Semester'),
        ),
        migrations.RemoveField(
            model_name='ngroup',
            name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='ngroup',
            unique_together=set([('name', 'year_of_foundation')]),
        ),
    ]
